name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose -f docker/test/docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run tests
        run: sleep 30 && docker-compose -f docker/test/docker-compose.yml run elkarbackup /run-tests.sh