name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test suite
        run: |
          docker-compose -f docker/test/docker-compose.yml up -d \
          && docker-compose -f docker/test/docker-compose.yml run elkarbackup /run-tests.sh